---
title: "Lab 1"
format: 
    html:
        embed-resources: true
code-fold: true
echo: true
theme: solar
---
[Task 1]{.underline}
Question 1
The aesthetics that are being used are the x-axis is income as GDP per capita, the y-axis is life expectancy, the color is the world region, the size of the bubbles is the population of the country, and individual bubbles represent individual countries.

Question 2
```{python}
import pandas as pd

df = pd.read_csv("C:/Users/andre/OneDrive/Documents/GSB 544/Week 1/Lab1_Data/q1data.csv")
df.head()
```

Question 3
```{python}
import plotnine as p9
from plotnine import ggplot, aes, geom_point, scale_size_continuous,scale_x_log10, ylim,scale_color_manual, labs, theme_minimal
plot = (
    p9.ggplot(df, p9.aes(
        x = "income",
        y = "life_exp",
        size = "population",
        color = "four_regions"
    ))
    + geom_point(alpha=0.7)
    + scale_size_continuous(range=(2,12))
    + scale_x_log10(breaks=[500,1000,2000,4000,8000,16000,32000,64000])
    + ylim(20, 90)
    + scale_color_manual(
        values={
            "europe":"yellow",
            "africa":"blue",
            "asia":"red",
            "americas":"green"
        }
    )
    +labs(
        x ="Income per person (GDP/capita, PPPS inflation adjusted)",
        y ="Life expectancy",
        color ="World Regions",
        title = "Income per person vs Life expectancy vs Population, 2010"
    )
    +theme_minimal()
)
plot
```

Question 4
```{python}
from plotnine import geom_boxplot
plot2 = (
    p9.ggplot(df, p9.aes(
        x = "four_regions",
        y = "life_exp",
        fill = "four_regions"
    ))
    + geom_boxplot()
    +labs(
        x="World Regions",
        y="Life expectancy",
        fill="World Regions",
        title = "Income per person vs Life Expectancy vs Population, 2010"
    )
    +theme_minimal()
)
plot2
```
This is an example of a bad geometry for visualizing our dataset because it does not get the point across that we are trying to make. Since it is a boxplot, we are unable to use the three continuous variables population, life expectancy, and income. We instead can only use one at a time.

[Task 2]{.underline}
Question 1
The aesthetics that are being used here are that the x-axis is exports, the y-axis is imports, the color of the bubbles are the world region, the size is energy use, and its a simple scatter plot with no log scaling.

Question 2
```{python}
df2 = pd.read_csv("C:/Users/andre/OneDrive/Documents/GSB 544/Week 1/Lab1_Data/q2data.csv")
df2.head()
```

Question 3
```{python}
from plotnine import coord_cartesian
df2["imports"] = df2["imports"].astype(float)
df2["exports"] = df2["exports"].astype(float)
df2["energy"] = df2["energy"].astype(float)
plot3= (
    p9.ggplot(
        df2, aes(
            x = "exports",
            y = "imports",
            color = "four_regions",
            size = "energy"
        )
    )
    + geom_point(alpha=0.7)
    + scale_size_continuous(range=(2,12), name="Energy use")
    + scale_color_manual(
        values={
            "europe":"yellow",
            "africa":"blue",
            "asia":"red",
            "americas":"green"
        })
    + coord_cartesian(xlim=(10,220), ylim=(0,400))
    +labs(
        x = "Exports (\% of GDP)",
        y = "Imports (\% of GDP)",
        color = "World Regions",
        title = "Exports vs Imports vs Energy use, 1997"
    )
    +theme_minimal()
)
plot3
```

Question 4
```{python}
from plotnine import geom_smooth
plot4 = (
    p9.ggplot(
        df2, aes(
            x = "exports",
            y = "imports",
            color = "four_regions"
        )
    )
    + geom_smooth(se=False)
    + scale_color_manual(
        values={
            "europe":"yellow",
            "africa":"blue",
            "asia":"red",
            "americas":"green"
        })
    +coord_cartesian(xlim=(10,220), ylim=(0,400))
    +labs(
        x = "Exports (\% of GDP)",
        y = "Imports (\% of GDP)",
        color = "World Regions",
        title = "Exports vs Imports, 1997"
    )
    +theme_minimal()
)
plot4
```
The problem with using this type of geometry is that we can't show each country's energy usage compared to their imports and exports. Another downside is that we can't see the individual points on the graph that represent individual countries.

[Task 3]{.underline}
Question 1
The aesthetics that are being used here is that the x-axis is Individuals using the internet, the y-axis is GDP per capita, the color represents the world region, the size of the bubbles represent income, and the graph follows a log scale.

Question 2
```{python}
df3 = pd.read_csv("C:/Users/andre/OneDrive/Documents/GSB 544/Week 1/Lab1_Data/q3data.csv")
df3.head()
```

Question 3
```{python}
from plotnine import scale_y_log10, scale_x_continuous, scale_size
df3["gdp"] = df3["gdp"].astype(float)
df3 = df3.dropna(subset=["gdp"])
plot5 = (
    p9.ggplot(
        df3,aes(
            x = "internet_users",
            y = "gdp",
            color = "four_regions",
            size = "income"
        )
    )
    + geom_point(alpha=0.7)
    + scale_x_continuous(breaks=[0,10,20,30,40,50,60,70,80,90], limits=[0,90])
    + scale_y_log10(breaks=[200,500,1000,2000,5000,10000,20000,50000,100000], labels=["200","500","1000","2000","5000","10k","20k","50k","100k"], limits=[200,100000])
    + scale_size(range=(2,12), name="Income")
    + scale_color_manual(
        values={
            "europe":"yellow",
            "africa":"blue",
            "asia":"red",
            "americas":"green"
        })
    + coord_cartesian(xlim=(0,90))
    + labs(
        x = "Individuals using the Internet",
        y = "GDP/capita",
        color = "World Regions",
        title = "Internet users vs GDP per capita, 2001"
    )
    +theme_minimal()
)
plot5
```

Question 4
```{python}
from plotnine import geom_jitter
plot6 = (p9.ggplot(df3,aes(
    x = "internet_users",
    y = "gdp",
    color = "four_regions",
    size = "income"
))
+ geom_jitter(alpha=0.6, width=1, height=0)
+ scale_y_log10(breaks=[200,500,1000,2000,5000,10000,20000,50000,100000], labels=["200","500","1000","2000","5000","10k","20k","50k","100k"], limits=[200,100000])
+ scale_color_manual(
        values={
            "europe":"yellow",
            "africa":"blue",
            "asia":"red",
            "americas":"green"
        })
+ coord_cartesian(xlim=(0,90))
+ labs(
    x = "Individuals using the Internet",
    y = "GDP/capita",
    color = "World Regions",
    title = "Internet users vs GDP per capita, 2001"
)
+ theme_minimal()
)
plot6
```
This type of geometry is just as good as the point geometry. It may even be better since the points don't overlap as much, so we are able to see the differences between the points better.